#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
INSTALL_DIR="/opt/misp-docker"; EXPOSURE="reverse-proxy"
while [[ $# -gt 0 ]]; do case "$1" in --install-dir) INSTALL_DIR="$2"; shift 2;; --exposure) EXPOSURE="$2"; shift 2;; *) fatal "Unknown argument: $1";; esac; done
acquire_operation_lock "$INSTALL_DIR"
[[ -d "$INSTALL_DIR" ]] || fatal "Install dir missing: $INSTALL_DIR"
cat > "$INSTALL_DIR/docker-compose.override.yml" <<'YAML'
# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
services:
  misp-core:
    healthcheck:
      test: curl -ksSf --max-time 2 https://localhost/users/heartbeat > /dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 60s
YAML
log "Rendered $INSTALL_DIR/docker-compose.override.yml ($EXPOSURE)."
